USE tempdb
GO

SELECT   nfHeader.valorTotal,
         nfHeader.cnpj,
         nfHeader.fone,
         nfHeader.xBairro,
         nfHeader.xLgr,
         nfHeader.xMun,
         nfHeader.xPais,
         nfHeader.uf,
         nfHeader.xFant,
         nfHeader.dhEmi,
         nfHeader.natOp,
         nfHeader.infCpl,
         nfHeader.vDesc,
         nfHeader.vFrete,
         nfHeader.vOutro,
         nfHeader.vProdIcms,
         nfHeader.vSeg,
         nfHeader.vTotTrib,
         nfHeader.vbc,
         nfHeader.vbcst,
         nfHeader.vcofins,
         nfHeader.vicms,
         nfHeader.vicmsDeson,
         nfHeader.vii,
         nfHeader.vipi,
         nfHeader.vnf,
         nfHeader.vpis,
         nfHeader.vst,
         nfHeader.versaoDocumento,
         nfItem.nItem,
         nfItem.indTot,
         nfItem.qCom,
         nfItem.uCom,
         nfItem.vProd,
         nfItem.vUnCom,
         nfItem.xProd
FROM     OPENROWSET (BULK 'D:\Mike\Totvs\sample.json', SINGLE_CLOB) J
         CROSS APPLY OPENJSON(REPLACE(BulkColumn, '$date', 'date'))
          WITH
           (
            valorTotal      FLOAT         '$.complemento.valorTotal',
            cnpj            CHAR(18)      '$.emit.cnpj',
            fone            VARCHAR(15)   '$.emit.enderEmit.fone',
            xBairro         VARCHAR(15)   '$.emit.enderEmit.Bairro',
            xLgr            VARCHAR(30)   '$.emit.enderEmit.xLgr',
            xMun            VARCHAR(30)   '$.emit.enderEmit.xMun',
            xPais           VARCHAR(30)   '$.emit.enderEmit.xPais',
            uf              VARCHAR(30)   '$.emit.enderEmit.uf',
            xFant           VARCHAR(30)   '$.emit.xFant',
            dhEmi           DATETIME      '$.ide.dhEmi.date',
            natOp           VARCHAR(30)   '$.ide.natOp',
            infCpl          VARCHAR(20)   '$.infAdic.infCpl',
            vDesc           FLOAT         '$.total.icmsTot.vDesc',
            vFrete          FLOAT         '$.total.icmsTot.vFrete',
            vOutro          FLOAT         '$.total.icmsTot.vOutro',
            vProdIcms       FLOAT         '$.total.icmsTot.vProd',
            vSeg            FLOAT         '$.total.icmsTot.vSeg',
            vTotTrib        FLOAT         '$.total.icmsTot.vTotTrib',
            vbc             FLOAT         '$.total.icmsTot.vbc',
            vbcst           FLOAT         '$.total.icmsTot.vbcst',
            vcofins         FLOAT         '$.total.icmsTot.vcofins',
            vicms           FLOAT         '$.total.icmsTot.vicms',
            vicmsDeson      FLOAT         '$.total.icmsTot.vicmsDeson',
            vii             FLOAT         '$.total.icmsTot.vii',
            vipi            FLOAT         '$.total.icmsTot.vipi',
            vnf             FLOAT         '$.total.icmsTot.vnf',
            vpis            FLOAT         '$.total.icmsTot.vpis',
            vst             FLOAT         '$.total.icmsTot.vst',
            versaoDocumento VARCHAR(30)   '$.versaoDocumento',
            items           NVARCHAR(MAX) '$.dets' AS JSON
           ) nfHeader
         CROSS APPLY OPENJSON(items)
          WITH
           (
            nItem  INT          '$.nItem',
            indTot INT          '$.prod.indTot',
            qCom   FLOAT        '$.prod.qCom',
            uCom   VARCHAR(10)  '$.prod.uCom',
            vProd  FLOAT        '$.prod.vProd',
            vUnCom FLOAT        '$.prod.vUnCom',
            xProd  VARCHAR(100) '$.prod.xProd'
           ) AS nfItem